---

- name: Include installation tasks
  ansible.builtin.include_tasks:
    file: install.yml
    apply:
      tags: ["install"]
  tags: ["install"]
  when:
    - ansible_os_family is defined
    - nfs_install

- name: Configure NFS shares
  ansible.builtin.blockinfile:
    path: /etc/exports
    content: "{{ lookup('template', 'exports.j2') }}"
  when: nfs_shares | length > 0
  notify: Reload NFS shares

- name: Include idmapping tasks
  ansible.builtin.include_tasks:
    file: idmapping.yml
    apply:
      tags: ["idmapping"]
  tags: ["idmapping"]
  when: nfs_idmapping_configure
